server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Explicitly removing or overriding strict CSP that might be set by Coolify Proxies
    # We allow 'unsafe-eval' so the JS minified code can run without being blocked
    add_header Content-Security-Policy "default-src * data: blob: 'unsafe-inline' 'unsafe-eval'; script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src * data: blob: 'unsafe-inline';" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
